version: '3.6'
services:
    bigdata_postgres:
        image: postgres:14.3-alpine
        restart: always               
        environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
        ports:
          - 5432:5432
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          placement:
            constraints:
              - node.hostname == kttv2      
        volumes:
          - bigdata_data_postgres:/var/lib/postgresql/data          
        logging:
          options:
            max-size: "5m"
            max-file: "10"
        networks:
          - hadoop
    
volumes:  
  bigdata_data_postgres:
    driver: local 
    driver_opts:
        type: none
        o: bind
        device: "/opt/bigdata/postgres"     
 
networks: 
  hadoop:   
    external: true