version: '3.6'
services:
    hadoop-master:
        image: ngovanmanh/hadoop:3.2.0
        hostname: 
        environment:
            - MONGO_CONNECTION=mongodb://admin:vienai%400258@ds1mongo.aiacademy.edu.vn:60001/?replicaSet=replicaAI&authSource=admin&authMechanism=SCRAM-SHA-1
        ports: 
            - 8513:1510        
            - 50070:50070
            - 60010:60010
            - 8088:8088
            - 9870:9870
        restart: always
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
            placement:
                constraints:
                    - node.hostname==ds1
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]       
        networks:
            - vienai_system_network
            
networks:
    vienai_system_network:
        external: true