version: '3.6'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zookeeper1_data:/data
      - zookeeper1_log:/datalog
    deploy:
      restart_policy:
          condition: on-failure
      replicas: 1
      # placement:
      #     constraints:
      #         - node.hostname==slave05
    networks:
      - hadoop

  zoo2:
    image: zookeeper
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zookeeper2_data:/data
      - zookeeper2_log:/datalog
    deploy:
      restart_policy:
          condition: on-failure
      replicas: 1
      # placement:
      #     constraints:
      #         - node.hostname==slave05
    networks:
      - hadoop

  zoo3:
    image: zookeeper
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zookeeper3_data:/data
      - zookeeper3_log:/datalog
    deploy:
      restart_policy:
          condition: on-failure
      replicas: 1
      # placement:
      #     constraints:
      #         - node.hostname==slave05
    networks:
      - hadoop


networks:
  hadoop:
      external: true

volumes:
  zookeeper1_data:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper1/data" 
  zookeeper1_log:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper1/log"
    
  zookeeper2_data:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper2/data" 
  zookeeper2_log:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper2/log"  

  zookeeper3_data:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper3/data" 
  zookeeper3_log:   
      driver: local     
      driver_opts:
          type: none
          o: bind
          device: "/opt/bigdata/zookeeper/zookeeper3/log"